- name: Copy Git SSH key to instances
  copy:
    src: "config/id_ed25519"
    dest: "~/.ssh/githubKey"
    owner: "ubuntu"
    group: "ubuntu"
    mode: 0600

- name: Add key to ssh agent
  become: yes
  shell: |
    eval "$(ssh-agent)"
    ssh-add /home/ubuntu/.ssh/githubKey


- name: Create project directory
  become: yes
  file:
    path: /home/ubuntu/project
    owner: ubuntu
    group: ubuntu
    mode: 775
    recurse: yes
    state: directory

- name: Clone Project repository
  become: yes
  shell: git clone git@github.com:atefehz/CCC--COMP90024-2023-.git --config core.sshCommand="ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/githubKey" 
  args:
    chdir: '/home/ubuntu/project'
      

